### ISSUE TITLE
Anima_on_started/compleleted will not work well at sometimes in Godot 4

### ISSUE THREAD

**Issue by hakuhan** [ceceppa/anima#33]
Hi! I just start to use this amazing tool. But there are few issues I got:

- anima_on_started/completed will not worked at some times:1. Lambda function. 2. None parameter function. 3. Function with array parameter.
- 

> For this issue. I checked from code(tween.gd). And I found that `fn.callv(args)` will not call function with none parameter
![图片](https://user-images.githubusercontent.com/18411187/236622151-e2eef611-19e5-4acd-aed4-553da2ca26f0.png)

- anima_on_started/completed may be called at almost same time.
![图片](https://user-images.githubusercontent.com/18411187/236622269-aeeabbab-dc14-4186-b202-f4e35914e473.png)

- I tried to get changing values from callbacks. Values maybe the final value not changing value(For instance form picture. Value in anima_on_started should be 100 not 70).

For first issue. I tried to remove "[null]" parameter from callabacks. And call "fn.call()" instead of "fn.callv(args)". But I also want to listent to your advice for this issue. 
For the rest issues. I didn't step deep into codes. 
Please take look if you have time. Thanks!

**Comment by ceceppa** [comment]
Yes, this PR fixes the issue: https://github.com/ceceppa/anima/pull/36.

The on_started not being called when using a null argument was caused by: https://github.com/ceceppa/anima/pull/36/files#diff-2a929f738ff4410e24f987f0c0c4a3b030487341a75e129618db01dbd7158fdeR42

The wrong order of calling because of the wrong delay: https://github.com/ceceppa/anima/pull/36/files#diff-a2f081ee8c7097b2792a05cfc65703a7c706e7dacdc82e6fa2c365bc079359e7L188
